### PR TITLE
Port package to autotools

### PR DESCRIPTION
**Pull request by ribalda**
These two patches port the tool to autotools so it can be easily build by cross complilation tools like OpenEmbedded.

### CODE REVIEW

**Comment by kirushyk** [comment]
Thank you

**Comment by kirushyk** [comment]
Can you please slightly tweak your 1st commit, I want to keep LGPL licence: even after porting to GStreamer's tracing subsystem, I think I need to keep an option to dynamically link libgstintercept to 3rd party things.

**Comment by ribalda** [comment]
this one http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt ?

I choose gpl becase https://github.com/kirushyk/gst-instruments/blob/master/instruments/gst-top.c

**Comment by ribalda** [comment]
My bad, it is of course LGPL. I fix and resubmit

**Comment by kirushyk** [comment]
Let's keep version 3 of LGPL.

**Comment by ribalda** [comment]
Like this?

**Pull request merged**
